[server]
host = "127.0.0.1"
port = 8080

[ethereum]
endpoint = "http://localhost:8545"

[starknet]
endpoint = "https://starknet-mainnet.public.blastapi.io"

[logging]
level = "debug"
log_file = "logs/test_starknet_fee_estimator.log"
max_file_size_mb = 5
max_files = 3
enable_console = true
